[build]
rustflags = ["--cfg=web_sys_unstable_apis"]

[unstable]
build-std = ["panic_abort", "std"]

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "-C", "link-arg=--max-memory=4294967296",
]
